image: docker:latest

before_script:
  - apk add --no-cache curl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
  - test
  - push_docker

test:
  stage: test
  script:
    - docker-compose -f docker-compose-test.yml up --exit-code-from idp-api-test --abort-on-container-exit
  only:
    - master

build_push_docker_image_tagged:
  stage: push_docker
  tags:
    - docker-build
  script:
    - docker-compose build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - export | grep -vi token
    - docker tag idp-api:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
