version: "3.2"

services:
  idp-api:
    build:
      context: .
      dockerfile: docker/idp-api/Dockerfile
    image: idp-api
    ports:
      - "8000:8000"
    env_file:
      - ./env-test
    container_name: idp-api-test
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    depends_on:
      - keycloak-server

  keycloak-server:
    image: jboss/5.0.0
    ports:
      - "8080:8080"
    networks:
      - default
    env_file:
      - ./env-test

networks:
  default:
