FROM golang:1.12-alpine3.9

WORKDIR /go/src/github.com/p53/idp-api
ENV GOPATH=/go

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
            git \
            gcc \
            g++ \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            curl
RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
COPY . /go/src/github.com/p53/idp-api

RUN dep ensure

COPY ./docker/idp-api/wait-for-keycloak.sh /opt
RUN chmod u+x /opt/wait-for-keycloak.sh

CMD ["/opt/wait-for-keycloak.sh", "/usr/local/go/bin/go", "test", "-v", "./..."]
